### ISSUE TITLE
Latest version available?

### ISSUE THREAD

**Issue by cpelley** [SciTools/mule#1]
Hi @stevewardle I see a 'release' [here](https://code.metoffice.gov.uk/doc/um/mule_utils/2017.06.1).

Is that the case?  Or is this not a formal release?

Chers

**Comment by stevewardle** [comment]
You do see a release, and it is a formal one *but* since this marks the first version of Mule which switches from using the UM-built packing library to using the standalone Shumlib library, there's slightly more work involved before I can support the release on Github

**Comment by cpelley** [comment]
OK NP, thanks for the reply.  We aren't in any desperate rush for the newer version to be made available.

Thanks @stevewardle.  I'll close this issue.
